# Generated by Django 5.0.4 on 2024-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryAndIndexInvestmentData', '0002_stockdata_delete_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table='stock_data',
        ),
        migrations.CreateModel(
            name='DividendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('dividend', models.FloatField()),
            ],
            options={
                'db_table': 'dividend_data',
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
