# Generated by Django 5.0.4 on 2024-05-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investmentDashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicLink',
        ),
        migrations.DeleteModel(
            name='InvestmentDashboard',
        ),
    ]
